project:
  type: website
  output-dir: _site

website:
  title: "WA Economic Indicators"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

execute:
  echo: false
  warning: false
  message: false